apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-api
  labels:
    app: ticketing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-api
  template:
    metadata:
      labels:
        app: ticketing-api
    spec:
      containers:
        - name: ticketing-api
          image: registry.ocp4.example.com:8443/developer/ticketing-api:1.3

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: ticketing-config

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-api
spec:
  selector:
    app: ticketing-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ticketing-api
spec:
  host: ticketing-api-ticketing-platform.apps.ocp4.example.com
  to:
    kind: Service
    name: ticketing-api
  port:
    targetPort: 8080