apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-viewer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ticketing-readonly
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ticketing-readonly-binding
subjects:
  - kind: ServiceAccount
    name: ticketing-viewer
    namespace: ticketing-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ticketing-readonly